# Generated by Django 5.2.5 on 2025-11-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bubble_text', models.CharField(max_length=500)),
                ('pub_time', models.DateTimeField(verbose_name='time published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubbles.user')),
            ],
        ),
    ]
